### ISSUE TITLE
Sending "false" on startup

### ISSUE THREAD

**Issue by DamianosS** [corbosman/node-red-contrib-timerswitch#16]
Hi, and thanks for the great work. I appreciate the valuable functionality!

I'm using the node for lawn and plant watering. I have just one issue: When modifying the node and deploying it, it sends a "false" on output. For some applications, this leads to unwanted behavior. 

Would it be possible to send the "false" still but with a specific topic (e.g., "initialize"), so we can distinguish it from other messages?

Thanks!

**Comment by corbosman** [comment]
Hi, I can't really reproduce this but maybe I do something different? When I drop a timerswitch node in a flow, add a debug to it, and deploy, I only see on or off as a msg, depending on the actual timer status.  I can't seem to get a false no matter what I do. This is on version 1.4.0.

**Comment by DamianosS** [comment]
Thanks, for the speedy reply! :) I'm able to reproduce it:

`
[{"id":"dee0f5f4c8d5efbd","type":"timerswitch","z":"7a1eefe0.e147b","name":"test","ontopic":"","offtopic":"","onpayload":"true","offpayload":"false","disabled":false,"schedules":[{"on_h":"10","on_m":"00","on_s":"00","off_h":"11","off_m":"00","off_s":"00","valid":true}],"x":430,"y":1840,"wires":[["292f3d2434c5b5d8"]]},{"id":"292f3d2434c5b5d8","type":"debug","z":"7a1eefe0.e147b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":1840,"wires":[]}]
`
My version is also 1.4.0

**Comment by DamianosS** [comment]
Maybe, the behavior is as expected? When the node is deployed, the message sent is (as you stated) "on" or "off", depending on the point in time. I understand that if I deploy the flow and the sprinkler should be on (because it's within the time boundaries) it will send an "on". 
However, when starting, the message sent reaches the targets because I can't distinguish if it's a regular or a starting message (to filter it out). That's why my suggestion was to combine it with a dedicated topic.

**Comment by corbosman** [comment]
Sorry just still trying to understand. The reason there is a startup msg is so that if the timer was not running during change of timer (so you missed an on or off) you still get one once the timer starts up. 

Now if you didn't miss a previous msg, all that happens (or should happen) is that you get an additional on/off, and my assumption is that it shouldn't matter. 

Situation 1: your sprinkler was off, RPI was not running. You reboot your RPI, sprinkler should have been on, startup msg sends an "on" and sprinklers turn on. 

Situation 2: your sprinkler was on, you redeploy (or reboot your RPI, or whatever), timer sends another on, which I assume to be redundant. 

I guess this could be a problem if your switch is a toggle.  I can't really send a topic for startup because people might be using the topic already, and expecting to see the normal on/off topic also on startup.

**Comment by DamianosS** [comment]
Hi @corbosman, I solved the situation by setting a filter node after the timerswitch node, blocking any unchanged messages.

Thanks for your effort!
