### ISSUE TITLE
Looking good but description is misleading

### ISSUE THREAD

**Issue by scargill** [corbosman/node-red-contrib-timerswitch#7]
Hi

Your timer node description states that multiple on-off times in a day is unique to your node. Not true, node-red-contrib-bigtimer can handle 2 on-off times a day and if there was a demand could handle more - so the description in that respect is wrong hence the "issue". It is however nice to see a simple timer out there with multiple times per day.

Regards

Pete

**Comment by corbosman** [comment]
Hi Pete, I think the subject of your issue is a little over the top. We're not competition. Having said that, since it obviously bothers you, I have removed the sentence.  Note though,  I wrote this code like 3 years ago. I specifically needed multiple on/off times, which had to be very accurate due to time sensitivity (think stuff like feeding fish pallets for 3 seconds. or running water misters for exactly 15 seconds).  BigTimer had neither at that time. I actually looked into writing a PR for your code, but 1) it wasnt on github so it didnt seem very inviting to submit modifications, and 2) the code was not really structured in a way that would allow for unlimited schedules in a single node. 

Things might have changed since, I dont know. I didnt really keep track. My node does exactly what I need and has been running my terrarium flawlessly for the last 3 years. Im not really after market share, you're totally welcome to it.

**Comment by scargill** [comment]
Hi there. Didn’t bother me, I just like accuracy. Modifications for BigTimer are always welcome, I didn’t put it on GIT simply as it is nothing more than an html file and a JS file, both of which you get when you download BigTimer. People ask for extra features all the time and often provide code or ideas. Provided I don’t lose compatibility for existing users (as there are lots of them) I’m usually happy with that. No, my code is not oriented towards arbitrary times per day, you are correct. As for market share, I do this for entertainment.

 

Regards

 

Pete
